- name: Configurar Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Instalar librerías de rastreo web
    run: |
      pip install beautifulsoup4 requests

  - name: Ejecutar el rastreador de Python
    run: |
      python scraper.py

  - name: Guardar y publicar vacantes.json actualizadas
    run: |
      git config --global user.name "Bot-RRHH-Noelia"
      git config --global user.email "bot@github.com"
      git add vacantes.json
      git commit -m "🤖 Actualización automática de vacantes de RRHH" || exit 0
      git push
