name: Recolector de Empleo RRHH Uruguay

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar script de búsqueda
        run: python scraper.py

      - name: Guardar y subir cambios al sitio
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualización automática de vacantes de RRHH"
          file_pattern: vacantes.json
